# Generated by Django 4.1.5 on 2023-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_rename_user_id_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="issues",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="issues",
            name="project_id",
            field=models.IntegerField(),
        ),
    ]
