# Generated by Django 4.1.5 on 2023-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_issues_id_alter_issues_project_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributors",
            name="role",
            field=models.CharField(
                choices=[("AUTHOR", "Author"), ("CONTRIBUTOR", "Contributor")],
                max_length=50,
            ),
        ),
    ]
